// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  chrome.tabs.onCreated.addListener(function(tab) {
    return Tab.last_open_tabs.push(tab);
  });

  chrome.tabs.onActivated.addListener(function(info) {
    chrome.tabs.get(info.tabId, function(tab) {
      if (tab && (tab !== Tab.now_tab)) {
        Tab.lastTab = Tab.now_tab;
        return Tab.now_tab = tab;
      }
    });
    return Vrome.setStatus();
  });

  chrome.tabs.onRemoved.addListener(function(tabId) {
    var tab;
    tab = Tab.now_tab;
    if ((tab != null ? tab.id : void 0) === tabId) {
      return Tab.addToClosedTabs(tab);
    }
  });

  $(function() {
    return Vromerc.init();
  });

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

}).call(this);
