// Generated by CoffeeScript 1.6.3
(function() {
  var checkReloadExtension, latestVersion, reloadExtension, root, time;

  latestVersion = null;

  time = 500;

  reloadExtension = function() {
    return chrome.tabs.query({
      url: "chrome://extensions-frame/"
    }, function(tabs) {
      var tab;
      if (tab = tabs[0]) {
        return chrome.tabs.reload(tab.id, {
          bypassCache: true
        });
      } else {
        chrome.tabs.create({
          url: "chrome://extensions-frame/",
          selected: false,
          pinned: true
        });
        return reloadExtension();
      }
    });
  };

  checkReloadExtension = function() {
    return $.post('http://127.0.0.1:20000', JSON.stringify({
      'method': 'get_latest_version'
    })).success(function(response) {
      if ((latestVersion !== null) && (latestVersion !== response)) {
        reloadExtension();
      }
      if (latestVersion === null) {
        chrome.tabs.reload({
          bypassCache: true
        });
      }
      return latestVersion = response;
    });
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.reloadExtension = reloadExtension;

  root.checkReloadExtension = checkReloadExtension;

  setInterval(checkReloadExtension, time);

}).call(this);
