// Generated by CoffeeScript 1.6.3
(function() {
  var Vrome, root;

  Vrome = (function() {
    var disableMap;

    function Vrome() {}

    disableMap = {};

    Vrome.setStatus = function() {
      return chrome.tabs.getSelected(null, function(tab) {
        if (disableMap[tab.id]) {
          chrome.browserAction.setIcon({
            path: 'images/logo-disable.png'
          });
          return chrome.browserAction.setTitle({
            title: 'Vrome (disabled)'
          });
        } else {
          chrome.browserAction.setIcon({
            path: 'images/logo.png'
          });
          return chrome.browserAction.setTitle({
            title: "Vrome (enabled)"
          });
        }
      });
    };

    Vrome.enable = function() {
      disableMap[getTab(arguments).id] = false;
      return Vrome.setStatus();
    };

    Vrome.disable = function() {
      disableMap[getTab(arguments).id] = true;
      return Vrome.setStatus();
    };

    return Vrome;

  }).call(this);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Vrome = Vrome;

}).call(this);
