// Generated by CoffeeScript 1.6.3
(function() {
  chrome.runtime.onMessage.addListener(function(msg, sender, sendResponse) {
    var action, argument, func, tab, _i, _len, _ref, _ref1;
    _ref = msg.action.split(".");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      action = _ref[_i];
      func = (func != null ? func : window)[action];
    }
    argument = (_ref1 = msg["arguments"]) != null ? _ref1 : msg;
    argument = (argument instanceof Array ? argument : [argument]);
    tab = sender.tab;
    if (tab) {
      tab.sendResponse = sendResponse;
    }
    argument.push(tab);
    if (func instanceof Function) {
      return func.apply("", argument);
    }
  });

}).call(this);
