// Generated by CoffeeScript 1.6.3
(function() {
  var m, root, _i, _len, _ref;

  this.getLocalServerUrl = function() {
    return "http://127.0.0.1:" + Option.get("server_port");
  };

  this.checkServerStatus = function() {
    return $.ajax(this.getLocalServerUrl()).done(function() {
      $("#server_status").attr("src", "/images/server_online.png");
      return $("#server_status").attr("alt", "Server Online");
    }).fail(function() {
      $("#server_status").attr("src", "/images/server_offline.png");
      return $("#server_status").attr("alt", "Server Offline. Run ./vrome");
    });
  };

  this.getHostname = function(href) {
    if (href) {
      return $("<a href='" + href + "'>").get(0).host;
    }
    return window.location.host || "file";
  };

  this.stringify = function(obj) {
    if ($.isArray(obj)) {
      return obj.join(", ");
    }
    if ($.isPlainObject(obj)) {
      return JSON.stringify(obj);
    }
    return obj;
  };

  this.rabs = function(num, total) {
    return (num % total + total) % total;
  };

  this.desc = function(func, description) {
    return func.description = description;
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  _ref = ["getLocalServerUrl", "checkServerStatus", "getHostname", "stringify", "rabs", "desc"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    m = _ref[_i];
    root[m] = self[m];
  }

}).call(this);
