// Generated by CoffeeScript 1.6.3
(function() {
  var Bookmark, root;

  Bookmark = (function() {
    function Bookmark() {}

    Bookmark.search = function(msg) {
      var drawDialog, keyword, tab, _ref;
      _ref = [getTab(arguments), msg.keyword], tab = _ref[0], keyword = _ref[1];
      drawDialog = function(historys) {
        return Post(tab, {
          action: "Dialog.draw",
          urls: historys,
          keyword: keyword
        });
      };
      return chrome.bookmarks.search(keyword, function(bookmarks) {
        if (keyword === "") {
          return chrome.bookmarks.getRecent(20, drawDialog);
        } else {
          return drawDialog(bookmarks);
        }
      });
    };

    return Bookmark;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Bookmark = Bookmark;

}).call(this);
