// Generated by CoffeeScript 1.6.3
(function() {
  var Clipboard, root;

  Clipboard = (function() {
    var createTextArea;

    function Clipboard() {}

    createTextArea = function(data) {
      var text_node;
      text_node = $("<textarea>").val(data);
      $('body').append(text_node);
      return text_node;
    };

    Clipboard.copy = function(msg) {
      var text_node;
      text_node = createTextArea(msg.value);
      text_node.select();
      document.execCommand("Copy");
      return $(text_node).remove();
    };

    Clipboard.read = function(msg) {
      var result, text_node;
      text_node = createTextArea("");
      text_node.select();
      document.execCommand("paste");
      result = $(text_node).val();
      $(text_node).remove();
      return result;
    };

    return Clipboard;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Clipboard = Clipboard;

}).call(this);
