// Generated by CoffeeScript 1.6.3
(function() {
  var Editor, root;

  Editor = (function() {
    function Editor() {}

    Editor.open = function(msg) {
      var tab;
      tab = getTab(arguments);
      return $.post(getLocalServerUrl(), JSON.stringify({
        method: "open_editor",
        editor: Option.get("editor"),
        data: msg.data,
        col: msg.col,
        line: msg.line
      })).fail(function() {
        runScript({
          code: "CmdBox.set({title : 'Failed to open external Editor, Please check Vrome WIKI opened in new tab for how to do',timeout : 15000});"
        }, tab);
        return chrome.tabs.create({
          url: "https://github.com/jinzhu/vrome/wiki/Support-External-Editor",
          index: tab.index + 1,
          selected: false
        });
      }).done(function(data) {
        return Post(tab, {
          action: msg.callbackAction,
          edit_id: msg.edit_id,
          value: data
        });
      });
    };

    return Editor;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Editor = Editor;

}).call(this);
