// Generated by CoffeeScript 1.6.3
(function() {
  var Frame, root;

  Frame = (function() {
    var current_frame_urls, nextUrl;

    function Frame() {}

    current_frame_urls = {};

    nextUrl = function(frames, current_frame_url, count) {
      var cur_index, frame, new_index, uniq_urls;
      uniq_urls = $.unique((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = frames.length; _i < _len; _i++) {
          frame = frames[_i];
          if (!/doubleclick\.|qzone\.qq\.com|plusone\.google\.com|about:blank/.test(frame.url)) {
            _results.push(frame.url);
          }
        }
        return _results;
      })()).reverse();
      cur_index = uniq_urls.indexOf(current_frame_url) || 0;
      new_index = rabs(cur_index + count, uniq_urls.length);
      return uniq_urls[new_index];
    };

    Frame.next = function(msg) {
      var tab;
      tab = getTab(arguments);
      return chrome.webNavigation.getAllFrames({
        tabId: tab.id
      }, function(frames) {
        current_frame_urls[tab.id] = nextUrl(frames, current_frame_urls[tab.id], msg.count);
        return Post(tab, {
          action: "Frame.select",
          href: current_frame_urls[tab.id]
        });
      });
    };

    return Frame;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Frame = Frame;

}).call(this);
