// Generated by CoffeeScript 1.6.3
(function() {
  var History, root;

  History = (function() {
    function History() {}

    History.search = function(msg) {
      var keyword, tab, _ref;
      _ref = [getTab(arguments), msg.keyword], tab = _ref[0], keyword = _ref[1];
      return chrome.history.search({
        text: keyword,
        startTime: 0
      }, function(historys) {
        return Post(tab, {
          action: "Dialog.draw",
          urls: historys,
          keyword: keyword
        });
      });
    };

    return History;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.History = History;

}).call(this);
