// Generated by CoffeeScript 1.6.3
(function() {
  var render, renderPages, saveOptions, saveSettings, setSettings, switchTab;

  render = function(elem, template) {
    return $.get(chrome.extension.getURL(template), function(data) {
      return elem.html(data);
    });
  };

  switchTab = function(tab_name) {
    $("nav #tabs li a").removeClass("selected");
    $("nav #tabs li a[href=" + tab_name + "]").addClass("selected");
    $("section .tabContent").hide();
    return $("" + tab_name + "Content").show();
  };

  renderPages = function() {
    render($("#dashboardContent"), "/README.html");
    render($("#settingContent"), "/files/setting.html");
    render($("#donatesContent"), "/files/donates.html");
    render($("#changelogContent"), "/files/changelog.html");
    render($("#thanksContent"), "/files/thanks.html");
    render($("#featuresContent"), "/files/features.html");
    switchTab(document.location.hash || "#setting");
    return $("nav #tabs li a").click(function() {
      return switchTab($(this).attr("href"));
    });
  };

  setSettings = function() {
    $("#vromerc").val(Settings.get("vromerc"));
    $("#onlineVromercUrl").val(Settings.get("onlineVromercUrl"));
    $("#onlineVromercReloadInterval").val(Settings.get("onlineVromercReloadInterval"));
    $("#onlineVromercLastUpdatedAt").val(Settings.get("onlineVromercLastUpdatedAt"));
    return changeAccessButtonStatus(oauth.hasToken());
  };

  saveSettings = function() {
    Settings.add({
      onlineVromercUrl: $("#onlineVromercUrl").val(),
      onlineVromercReloadInterval: $("#onlineVromercReloadInterval").val(),
      vromerc: Vromerc.parse($("#vromerc").val())
    });
    return window.setTimeout(setSettings, 100);
  };

  saveOptions = function() {
    saveSettings();
    Vromerc.loadAll();
    return $("#saved").show().fadeOut(3000);
  };

  $(function() {
    renderPages();
    window.setTimeout(setSettings, 500);
    window.setInterval(checkServerStatus, 1000);
    $('body').on('click', ".saveOptions", saveOptions);
    $('body').on('click', ".closeWindow", window.close);
    $('body').on('click', "#grantAccess", grantOAuthAccess);
    return $('body').on('click', "#revokeAccess", revokeOAuthAccess);
  });

}).call(this);
