// Generated by CoffeeScript 1.6.3
(function() {
  var applyEvents;

  applyEvents = function() {
    $(".openOptionsFeatures").click(function() {
      return openOptions("features");
    });
    $(".openOptionsSetting").click(function() {
      return openOptions("setting");
    });
    $(".openOptionsChangelog").click(function() {
      return openOptions("changelog");
    });
    $(".openOptionsDonates").click(function() {
      return openOptions("donates");
    });
    $(".openSourcePage").click(openSourcePage);
    $(".openChromeStore").click(openChromeStore);
    $(".openIssuesPage").click(openIssuesPage);
    return $(".version").text(Settings.get("version"));
  };

  $(function() {});

  $(function() {
    return window.setTimeout(applyEvents, 500);
  });

}).call(this);
