// Generated by CoffeeScript 1.6.3
(function() {
  var root, shortUrl;

  shortUrl = function(msg) {
    var auth, headers, params, sendBackCurrentUrl, server_url, tab, _ref;
    sendBackCurrentUrl = function() {
      return Post(tab, {
        action: "Url.shortUrl",
        url: tab.url
      });
    };
    _ref = [getTab(arguments), oauth.hasToken()], tab = _ref[0], auth = _ref[1];
    server_url = "https://www.googleapis.com/urlshortener/v1/url";
    headers = {
      "Content-type": "application/json"
    };
    if (auth) {
      headers["Authorization"] = oauth.getAuthorizationHeader(server_url, "POST");
    }
    params = {
      type: "POST",
      url: server_url,
      headers: headers,
      data: JSON.stringify({
        longUrl: encodeURI(tab.url)
      })
    };
    return $.ajax(params).fail(sendBackCurrentUrl).done(function(response) {
      var _ref1;
      if (((_ref1 = response.error) != null ? _ref1.code : void 0) === "401") {
        oauth.clearTokens();
        return sendBackCurrentUrl();
      } else {
        return Post(tab, {
          action: "Url.shortUrl",
          url: response.id
        });
      }
    });
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.shortUrl = shortUrl;

}).call(this);
