"use strict";(function(){var a=devhd.pkg("pages");var c=devhd.i18n.L;var b=devhd.log.get("page.my");a.MyPage=function(){};var f=a.MyPage.prototype=new a.BasePage();f.service=function(h,g){this.pageInfo=h;this.width=g.width;this.categoryLabel="#"+h.type;this.eos=h.preferences["entryOverviewSize.desktop"]||4;this.initBase(g);this.startRenderHTML()};f.destroy=function(){if(this.topArea!=null){this.topArea.destroy();
this.topArea=null}this.entryIndex=null;this.allIds=null;this.entries=null;this.summary=null;this.recs=null;this.c2e=null;this.destroyBase()};f.isLayoutAware=function(){return true};f.allowsSideArea=function(g){if(g.searchTerm!=null){return true}return g.preferences["entryOverviewSize.desktop"]!=0&&g.preferences["entryOverviewSize.desktop"]!=5};f.allowsSearch=function(){return true
};f.getSearchScope=function(){return devhd.utils.IdUtils.formatId("category","global.all",this.home.getUserId())};f.showCustomizer=function(i){var h={};var g=this.getPreference("entryOverviewSize.desktop");switch(g){case"0":h.view="lvc_u0";break;case"5":h.view="lvc_u5";break;case"4":default:h.view="lvc_u4"}if(this.popup!=null){this.popup.show(templates.page.base.popupMyCustomizer(this.pageInfo,h,this.home),i.target,{minWidth:167,deltaLeft:0,deltaTop:3,orientation:"SW"},this)
}};f.startRenderHTML=function(){try{this._cancelAllVisualFinders();this.entryIndex={};this.endOfList=null;this.state="loading";this.selectedEntryId=null;var g=this.hideReadArticlesFilter()?"read":null;this.feedly.pushContext({uri:this.pageInfo.uri,title:"digest",pageNumber:this.pageInfo.pageNumber,level:1,queryInfo:{flsId:this.categoryLabel,excludeLabel:g},category:this.categoryLabel});
this.trackTime("pushed context");this.feedly.enableMarkAsRead();this.feedly.enableRefresh();this.feedly.clearNbrPages();this.feedly.setPageTitle(templates.page.my.title());this.trackTime("updated chrome");var h=this;this.reader.askSections({excludeEmpty:true},function(k){e.call(h,k)})}catch(i){var j=devhd.utils.ExceptionUtils.formatError("layout top area",i);
this.pageElem.innerHTML=j}};function e(m){try{if(m.length==0){this.displayEmptyMessage();return}this.pageElem.innerHTML=templates.page.my.layout(m,this.eos,this.width,this.home);this.trackTime("initial layout");this.entries=[];this.c2e={};this.allIds=[];var i=this;var h=6;var l=i.getPreference("featuredArticles")=="yes";var g=devhd.utils.DurationUtils.DAYS(3);
if(this.eos==0){h=12;l=false;g=devhd.utils.DurationUtils.DAYS(3)}else{if(this.eos==5){h=1;l=false;g=devhd.utils.DurationUtils.DAYS(7)}}this.reco.askStreamDigest({featured:l,count:h,timeframe:g},function(){if(i.isDestroyed()==true){return}for(var r=0;r<m.length;r++){var o=i.c2e[m[r].label];if(o==null){continue}for(var q=0;q<o.length;q++){var p=o[q];i.entryIndex[p.getId()]=p;
i.entries.push(p);i.allIds.push(p.getId())}}if(i.allIds.length==0){i.signs.setNextAutoHideDelay(7000);i.signs.setMessage("No Unread Articles. All Done!")}if(i.home.isProPlan()==false&&i.allIds.length>10||(i.eos==5&&i.allIds.length>=2)){var n=i.reader.computeTagCloud("#all").slice(0,20);var t=[];for(var r=0;r<n.length;r++){t.push(n[r].label.toLowerCase())
}var s;if(i.eos==0){s=3}else{if(i.eos==5){s=1}else{s=3}}i.reader.askPromotedEntries(t,s,true,devhd.utils.DurationUtils.HOURS(48),function(u){i.processPromotedEntries(u)},function(){$feedly("[my] failed to get promoted entries:"+JSON.stringify(t))})}},function(n,o){},function(o){try{if(i.isDestroyed()==true){return}for(var n=0;n<o.length;n++){d.call(i,o[n])
}}catch(p){$feedly("[my] failed to process parts:"+p.name+" -- "+p.message)}})}catch(j){var k=devhd.utils.ExceptionUtils.formatError("layout top area",j);this.pageElem.innerHTML=k}}function d(h){switch(h.label){case"#top":try{var r=this.element("topArea");if(r==null){this.pageElem.innerHTML="failed to lookup top area element";return}if(h.top40.length==0){this.element("main_#featured").style.display="none";
return}h.top40=this.pickFeaturedEntries(h.top40);this.topArea=new devhd.control.RecommendationAreaControl();this.topArea.setHome(this.home);this.topArea.setReader(this.reader);this.topArea.setFeatured(h.top40);this.topArea.setPage(this);this.topArea.setPart(r);this.topArea.display();for(var m=0;m<h.top40.length;m++){this.allIds.push(h.top40[m].getId());
this.entries.push(h.top40[m])}this.c2e["#featured"]=new Array().concat(h.top40)}catch(p){$feedly("[my] failed to process #top part:"+p.name+" -- "+p.message)}break;default:var n=this.element("main_section_"+h.label+"_entries");if(n==null){return}var q=h.top40;var o=[];if(this.eos==5){if(q.length==0){n.innerHTML=templates.page.my.noRecentEntries()}else{var l=[];
for(var k=0;k<q.length;k++){l.push({entry:q[k],type:k==0?5:13});o.push(q[k])}n.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true,clear:"both"},this.home);this.askFindVisual(q[0],"U5")}}else{if(this.eos==1||this.eos==0){if(q.length==0){if(h.feedId!=null){this.element("main_section_"+h.feedId+"_holder").style.display="none"
}else{this.element("main_section_"+h.label+"_holder").style.display="none"}this.c2e[h.label]=[];return}var l=[];for(var k=0;k<q.length;k++){l.push({entry:q[k],type:this.eos});o.push(q[k])}n.className=n.className+" u1EntryList";n.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true,clear:"both"},this.home)
}else{if(q.length==0){if(h.feedId!=null){this.element("main_section_"+h.feedId+"_holder").style.display="none"}else{this.element("main_section_"+h.label+"_holder").style.display="none"}this.c2e[h.label]=[];return}var g=Math.ceil(q.length-3);if(g<4){g=4}var l=[];for(var k=0;k<q.length&&k<g;k++){l.push({entry:q[k],type:this.eos});o.push(q[k])}n.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home);
for(var k=0;k<q.length&&k<g;k++){this.askFindVisual(q[k],"U4")}l=[];for(var k=g;k<q.length;k++){l.push({entry:q[k],type:12});o.push(q[k])}if(l.length>0){this.element("main_section_"+h.label+"_saved").innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)
}}}this.askAdjustEntries(q);this.c2e[h.label]=o}}f.processPromotedEntries=function(k){if(k.length==0){return}var m=this.element("main_section_feedly.promoted_entries");if(m==null){return}var g=[];if(this.eos==5){var l=[];for(var i=0;i<k.length;i++){l.push({entry:k[i],type:i==0?5:13});g.push(k[i])}m.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:false,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true,clear:"both"},this.home);
this.askFindVisual(k[0],"U5")}else{if(this.eos==1||this.eos==0){var l=[];for(var i=0;i<k.length;i++){l.push({entry:k[i],type:this.eos});g.push(k[i])}m.className=m.className+" u1EntryList";m.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true,clear:"both"},this.home)
}else{var h=1;var l=[];for(var i=0;i<k.length&&i<h;i++){l.push({entry:k[i],type:this.eos});g.push(k[i])}m.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home);for(var i=0;i<k.length&&i<h;i++){this.askFindVisual(k[i],"U4")}l=[];for(var i=h;i<k.length;
i++){l.push({entry:k[i],type:12});g.push(k[i])}if(l.length>0){this.element("main_section_feedly.promoted_saved").innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)}}}this.element("main_section_feedly.promoted_holder").style.display="block";this.analytics.trackEvent("promoted","home",k[0].getFeedId())
};f.markSectionAsRead=function(k){var h=[];var l=this.c2e[k];for(var g=0;g<l.length;g++){h.push(l[g].getId())}var j=this;this.reader.askMarkEntriesAsRead(h,function(){},function(i){j.signs.setMessage("Error:"+i)})};f.markPageAsRead=function(){this.signs.setMessage(c(87),100);var g=this;this.home.getDocument().defaultView.setTimeout(function(){g.reader.askMarkEntriesAsRead(g.allIds,function(){},function(h){g.signs.setMessage("Error:"+h)
})},15)};f.markAsRead=f.markPageAsRead;f.onSubscriptionMarkedAsRead=function(g){var h=this.element("main_section_"+g+"_holder");if(h!=null){this.effects.fade(h,{delay:1,from:1,to:0,onComplete:function(i){devhd.utils.HTMLUtils.remove(i)}},"feedly")}};f.onSubscriptionRemoved=function(g,i){if(i==true){return}var h=this.element("main_section_"+g+"_holder");
if(h!=null){this.effects.fade(h,{delay:1,from:1,to:0,onComplete:function(j){devhd.utils.HTMLUtils.remove(j)}},"feedly")}else{this.feedly.reloadPage()}};f.findNextEntryId=function(l){var k=false;if(this.selectedEntryId==null){k=true}for(var j=0;j<this.entries.length;j++){var h=this.entries[j].getId();if(k==true){var g=this.entries[j];if(g.jsonInfo.buried==true){continue
}if(l==true){if(g.isRead()==false){return h}else{continue}}else{return h}}if(h==this.selectedEntryId){k=true}}return null};f.findPreviousEntryId=function(l){var k=false;if(this.selectedEntryId==null){k=true}for(var j=this.entries.length-1;j>=0;j--){var h=this.entries[j].getId();if(k==true){var g=this.entries[j];if(g.jsonInfo.buried==true){continue}if(l==true){if(g.isRead()==false){return h
}else{continue}}else{return h}}if(h==this.selectedEntryId){k=true}}return null};f.onPreviousEntry=function(i,g){var h=this.findPreviousEntryId(i);if(h!=null){if(g==true){this.selectEntry(h,"toview")}else{this.inlineEntry(h,true,true)}}else{this.signs.setMessage(c(91))}};f.onNextEntry=function(i,g){var h=this.findNextEntryId(i);if(h!=null){if(g==true){this.selectEntry(h,"toview")
}else{this.inlineEntry(h,true,true)}}else{this.signs.setMessage(c(92))}}})();