"use strict";(function(){var d="pk_test_yoj2w7adyCRkmi35iS2f3TMK";var b="pk_live_atMEGqPDeLwMkj1NC8K1tZ32";var a=devhd.pkg("pages");a.ProPage=function(){};var c=a.ProPage.prototype=new a.BasePage();c.allowsSideArea=function(){return false};c.allowsPageHeader=function(){return false};c.service=function(f,e){this.pageInfo=f;this.width=e.width;this.feature=f.key;
this.initBase(e);if(this.home.isProPlan()){this.feedly.redirect("upgraded");return}this.feedly.closeMessageBar(true);this.startRenderHTML()};c.destroy=function(){this.destroyBase()};c.startRenderHTML=function(){try{var f=this.home.getDocument().createElement("script");f.type="text/javascript";f.src="https://checkout.stripe.com/v2/checkout.js";this.home.getDocument().getElementsByTagName("head")[0].appendChild(f)
}catch(h){this.signs.setMessage("failed to activate stripe:"+h.name+" -- "+h.message);return}if(this.feature!=null){this.analytics.trackPageview("sales/pro/"+this.feature);this.analytics.trackEvent("sales.pro",this.feature,this.home.getUserId()==null?"guest":"user")}var g=this.home.isStoreOpen()||this.feature=="abracadabra";this.feedly.setPageTitle("feedly Pro");
this.pageElem.innerHTML=templates.page.pro.layout(this.home.getUserId()!=null,this.home.isProPlan(),this.feature,g||this.feature=="checkout45"||this.feature=="blackfriday"||this.feature=="checkout5");if(this.feature=="checkout45"){this.startCheckout45()}else{if(this.feature=="checkout5"){this.startCheckout5()}else{if(this.feature=="blackfriday"){this.startCheckoutBlackFriday()
}else{if(this.feature=="checkoutLifetime"){this.startCheckoutLifetime()}else{this.analytics.trackPageview("sales/pro/datasheet");this.analytics.trackEvent("sales.pro","datasheet",this.home.getUserId()==null?"guest":"user")}}}}};c.startCheckout5=function(){var f=this;try{StripeCheckout.open({key:this.home.getDocument().defaultView.location.hostname.indexOf("sandbox.feedly.com")>-1?d:b,address:false,amount:500,currency:"usd",name:"Feedly Pro",description:"Monthly",panelLabel:"Upgrade",token:function(e){f.handlePayment(e,"FeedlyProMonthly")
},image:"https://s3.feedly.com/img/feedly-pro-payment-icon-128.png"});this.analytics.trackPageview("sales/pro/checkout5");this.analytics.trackEvent("sales.pro","checkout5",this.home.getUserId()==null?"guest":"user")}catch(g){if(this.retrying==null){this.retrying=true;this.signs.setMessage("Loading stripe...");var f=this;this.home.getDocument().defaultView.setTimeout(function(){f.startCheckout5()
},2500)}}};c.startCheckout45=function(){var f=this;try{StripeCheckout.open({key:this.home.getDocument().defaultView.location.hostname.indexOf("sandbox.feedly.com")>-1?d:b,address:false,amount:4500,currency:"usd",name:"Feedly Pro",description:"Yearly",panelLabel:"Upgrade",token:function(e){f.handlePayment(e,"FeedlyProYearly")},image:"https://s3.feedly.com/img/feedly-pro-payment-icon-128.png"});
this.analytics.trackPageview("sales/pro/checkout45");this.analytics.trackEvent("sales.pro","checkout45",this.home.getUserId()==null?"guest":"user")}catch(g){if(this.retrying==null){this.retrying=true;this.signs.setMessage("Loading stripe...");var f=this;this.home.getDocument().defaultView.setTimeout(function(){f.startCheckout45()},2500)}}};c.startCheckoutBlackFriday=function(){var f=this;
try{StripeCheckout.open({key:this.home.getDocument().defaultView.location.hostname.indexOf("sandbox.feedly.com")>-1?d:b,address:false,amount:3500,currency:"usd",name:"Feedly Pro",description:"Holiday Special",panelLabel:"Upgrade",token:function(e){f.handlePayment(e,"FeedlyProYearlyBlackFridayCoupon")},image:"https://s3.feedly.com/img/feedly-pro-payment-icon-128.png"});
this.analytics.trackPageview("sales/pro/blackfriday");this.analytics.trackEvent("sales.pro","blackfriday",this.home.getUserId()==null?"guest":"user")}catch(g){if(this.retrying==null){this.retrying=true;this.signs.setMessage("Loading stripe...");var f=this;this.home.getDocument().defaultView.setTimeout(function(){f.startCheckoutBlackFriday()},2500)}}};
c.startCheckoutLifetime=function(){var f=this;try{StripeCheckout.open({key:this.home.getDocument().defaultView.location.hostname.indexOf("sandbox.feedly.com")>-1?d:b,address:false,amount:29900,currency:"usd",name:"Feedly Pro",description:"Lifetime",panelLabel:"Upgrade",token:function(e){f.handlePayment(e,"FeedlyProLifetime")},image:"https://s3.feedly.com/img/feedly-pro-payment-icon-128.png"});
this.analytics.trackPageview("sales/pro/checkoutLifetime");this.analytics.trackEvent("sales.pro","checkoutLifetime",this.home.getUserId()==null?"guest":"user")}catch(g){if(this.retrying==null){this.retrying=true;this.signs.setMessage("Loading stripe...");var f=this;this.home.getDocument().defaultView.setTimeout(function(){f.startCheckoutLifetime()},2500)
}}};c.handlePayment=function(e,g){if(e.id!=null){this.analytics.trackPageview("sales/pro/"+g+"/approved");this.analytics.trackEvent("sales.pro",g+".approved",this.home.getUserId()==null?"guest":"user");this.disableButtons();var f=this;$feedly("[feedly] starting upgrade: "+devhd.utils.JSONUtils.encode(e)+" -- "+g);this.home.service("io").post("!{cloud}/v3/payment?stripeToken="+encodeURIComponent(e.id)+"&userId="+f.home.getUserId()+"&productId="+g+"&ck="+new Date().getTime()+"&ct=feedly.desktop&cv="+feedlyApplicationVersion,"",function(h){try{f.analytics.trackPageview("sales/pro/"+g+"/upgraded");
f.analytics.trackEvent("sales.pro",g+".upgraded",f.home.getUserId()==null?"guest":"user");f.disableButtons("Processing complete!");$feedly("[feedly] upgrade successful. "+h);var k=devhd.utils.JSONUtils.decode(h);var j=devhd.utils.SessionUtils.load();j.feedlyToken=k.accessToken;j.plan="pro";devhd.utils.SessionUtils.save(j);window.setTimeout(function(){window.location.reload(true)
},100)}catch(i){$feedly("Upgrade failed:"+i.name+" -- "+i.message);window.alert("Please reload feedly to access your new feedly Pro account");f.analytics.trackPageview("sales/pro/"+g+"/error");f.analytics.trackEvent("sales.pro",g+".error",i.name)}},function(h,l){if(h==403){var j="Your card was declined.";try{var i=devhd.utils.JSONUtils.decode(l);if(i!=null&&i.errorMessage!=null){j=i.errorMessage
}}catch(k){$feedly("[pro] failed to extract error message:"+l)}f.disableButtons(j,"Please reload the page and retry.");f.analytics.trackPageview("sales/pro/"+g+"/declined");f.analytics.trackEvent("sales.pro",g+".declined",403)}else{if(h==504){f.disableButtons("Processing timed out: "+h+" -- "+l,"Please try to log out and log back in.");f.analytics.trackPageview("sales/pro/"+g+"/timeout");
f.analytics.trackEvent("sales.pro",g+".timeout",504)}else{f.disableButtons("Processing failed: "+h+" -- "+l,"Sorry! If you have questions, please email us at payment@feedly.com with the above error info.");f.analytics.trackPageview("sales/pro/"+g+"/failed");f.analytics.trackEvent("sales.pro",g+".failed",h)}}},"application/json",{"$Authorization.feedly":"$FeedlyAuth","Content-Type":"application/json"})
}};c.disableButtons=function(h,g){var e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"already"});for(var f=0;f<e.length;f++){e[f].innerHTML=h||"Processing payment. Please wait..."}e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"button"});for(var f=0;f<e.length;f++){e[f].className="already";e[f].innerHTML=h||"Processing payment. Please wait..."
}if(g!=null){e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"note"});for(var f=0;f<e.length;f++){e[f].innerHTML=g}}}})();