// Generated by CoffeeScript 1.6.3
(function() {
  var addErrorLogger, err, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Post = function(msg) {
    return chrome.runtime.sendMessage(msg, function(response) {});
  };

  addErrorLogger = function() {
    return window.addEventListener("error", (function(err) {
      return Debug(err);
    }), false);
  };

  try {
    runIt(Settings.init, function() {
      var func, _i, _len, _ref, _results;
      _ref = [Zoom.init, KeyEvent.init, Custom.runJS, Custom.loadCSS];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        func = _ref[_i];
        _results.push(func.call());
      }
      return _results;
    });
    runIt(addErrorLogger);
  } catch (_error) {
    err = _error;
    Debug(err);
  }

}).call(this);
