// Generated by CoffeeScript 1.6.3
(function() {
  var AutoLink, root;

  AutoLink = (function() {
    var textNodes, url_regexp;

    function AutoLink() {}

    url_regexp = /(((https?|ftp|file):\/\/)?([\w]{2,}\.)+[\w]{2,5}(\/[\S]+)*)/g;

    textNodes = function(elems) {
      var e, _i, _len, _ref, _ref1, _results;
      _results = [];
      for (_i = 0, _len = elems.length; _i < _len; _i++) {
        e = elems[_i];
        if (((_ref = e.data) != null ? _ref.match(url_regexp) : void 0) && (e.nodeType === 3) && ((_ref1 = e.nodeName) !== "INPUT" && _ref1 !== "TEXTAREA")) {
          _results.push(e);
        }
      }
      return _results;
    };

    AutoLink.makeLink = function(elems) {
      var elem, value, _i, _len, _results;
      if (elems == null) {
        elems = null;
      }
      elems = textNodes(elems || jQuery("*:visible").not("iframe").contents());
      _results = [];
      for (_i = 0, _len = elems.length; _i < _len; _i++) {
        elem = elems[_i];
        if (jQuery(elem).parent().prop("tagName") !== 'A') {
          value = jQuery(elem).text().replace(url_regexp, function($0, $1) {
            return "<a href='" + (/^(\w+\.)+\w+/.test($1) ? "http://" + $1 : $1) + "'>" + $1 + "</a>";
          });
          _results.push(jQuery(elem).after(value).remove());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    desc(AutoLink.makeLink, "Transforms URLs into clickable links");

    return AutoLink;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.AutoLink = AutoLink;

}).call(this);
