// Generated by CoffeeScript 1.6.3
(function() {
  var Bookmark, root;

  Bookmark = (function() {
    var search;

    function Bookmark() {}

    search = function(keyword) {
      return Post({
        action: "Bookmark.search",
        keyword: keyword
      });
    };

    Bookmark.start = function(new_tab) {
      return Dialog.start({
        title: "Bookmark",
        search: search,
        newtab: new_tab
      });
    };

    desc(Bookmark.start, "Filter bookmarks with keyword (support Dialog extend mode)");

    Bookmark.newTabStart = function() {
      return Bookmark.start(true);
    };

    return Bookmark;

  }).call(this);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Bookmark = Bookmark;

}).call(this);
