// Generated by CoffeeScript 1.6.3
(function() {
  var Clipboard, root;

  Clipboard = (function() {
    function Clipboard() {}

    Clipboard.copy = function(value) {
      return Post({
        action: "Clipboard.copy",
        value: value
      });
    };

    return Clipboard;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Clipboard = Clipboard;

}).call(this);
