// Generated by CoffeeScript 1.6.3
(function() {
  var Completer, root;

  Completer = (function() {
    var db, sql;

    function Completer() {}

    db = openDatabase('vrome', '1.0', 'Vrome Data', 100 * 1024 * 1024);

    sql = function(str) {
      return db.executeSql(str);
    };

    Completer.build_index = function() {
      sql('CREATE TABLE IF NOT EXISTS urls (id NUMERIC DEFAULT 0, url TEXT, title TEXT, frecency NUMERIC DEFAULT -1)');
      return sql('INSERT OR REPLACE INTO urls (url, type, title, frecency, queuedfordeletion, typedVisitIds) VALUES (?, ?, ?, ?, ?, ?)', [historyItem.url, 1, historyItem.title, frecency, 0, visitId]);
    };

    return Completer;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Completer = Completer;

}).call(this);
