// Generated by CoffeeScript 1.6.3
(function() {
  var Custom, root;

  Custom = (function() {
    function Custom() {}

    Custom.loadCSS = function() {
      var customCSS;
      customCSS = Settings.get("@configure.css");
      if (customCSS) {
        return $("head").append($("<style>", {
          "class": '__vrome_custom_css',
          text: customCSS
        }));
      }
    };

    Custom.runJS = function() {
      var customJS;
      customJS = Settings.get("@configure.js");
      if (customJS) {
        return $("body").append($("<script>", {
          "class": '__vrome_custom_js',
          text: customJS
        }));
      }
    };

    return Custom;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Custom = Custom;

}).call(this);
