// Generated by CoffeeScript 1.6.3
(function() {
  var Debug, root;

  Debug = function(str) {
    var err;
    try {
      if ((typeof str === 'object') && str.hasOwnProperty('stack') && str.hasOwnProperty('message')) {
        str = "" + str.message + "\n\n" + str.stack;
      }
      if ($.isFunction(str)) {
        str = str.toString();
      }
      console.log(str);
      return Post({
        action: "Debug",
        message: str
      });
    } catch (_error) {
      err = _error;
      return console.log(err);
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Debug = Debug;

}).call(this);
