// Generated by CoffeeScript 1.6.3
(function() {
  var Frame, root;

  Frame = (function() {
    function Frame() {}

    Frame.select = function(msg) {
      var area, borderWas, code;
      if (location.href === msg.href) {
        area = innerWidth * innerHeight;
        if (area <= 100) {
          return Post({
            action: "Frame.next",
            count: 1
          });
        }
        window.focus();
        borderWas = document.body.style.border;
        document.body.scrollIntoViewIfNeeded();
        document.body.style.border = "5px solid yellow";
        setTimeout((function() {
          return document.body.style.border = borderWas;
        }), 200);
        code = "CmdBox.set({ title : 'Switched Frame To:" + document.location.href + "',timeout : 2000});";
        return Post({
          action: "runScript",
          code: code
        });
      }
    };

    Frame.next = function() {
      return Post({
        action: "Frame.next",
        count: times()
      });
    };

    desc(Frame.next, "Next {count} frame");

    Frame.prev = function() {
      return Post({
        action: "Frame.next",
        count: 0 - times()
      });
    };

    desc(Frame.prev, "Prev {count} frame");

    return Frame;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Frame = Frame;

}).call(this);
