// Generated by CoffeeScript 1.6.3
(function() {
  var Help, root;

  Help = (function() {
    var escape;

    function Help() {}

    Help.maps = [];

    escape = function(value) {
      return ('' + value).escape();
    };

    Help.add = function(key, func_name, func, mode) {
      if (func.description) {
        return this.maps.push([escape(key), escape(func_name), escape(func.description), mode]);
      }
    };

    Help.show = function() {
      var help_box, map, result_box, results;
      results = "<tr class='head'><td>Value</td><td>Description</td><td>Modes</td></tr>";
      results += ((function() {
        var _i, _len, _ref, _results;
        _ref = this.maps;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          map = _ref[_i];
          _results.push("<tr><td>" + map[0] + "</td><td>" + map[2] + "</td><td>" + map[3] + "</td></tr>");
        }
        return _results;
      }).call(Help)).join();
      result_box = $("<div>", {
        id: '__vrome_help_box',
        html: "<table>" + results + "</table>"
      });
      help_box = $("<div>", {
        id: '__vrome_help_overlay',
        html: result_box
      });
      return $("body").append(help_box);
    };

    desc(Help.show, "Open help page");

    Help.hide = function(reset) {
      return $("#__vrome_help_overlay").remove();
    };

    return Help;

  }).call(this);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Help = Help;

}).call(this);
