// Generated by CoffeeScript 1.6.3
(function() {
  var History, root;

  History = (function() {
    var search;

    function History() {}

    search = function(keyword) {
      return Post({
        action: "History.search",
        keyword: keyword
      });
    };

    History.start = function(new_tab) {
      return Dialog.start({
        title: "History",
        search: search,
        newtab: new_tab
      });
    };

    desc(History.start, "Filter History with keyword (support Dialog extend mode)");

    History.newTabStart = function() {
      return History.start(true);
    };

    History.back = function() {
      return history.go(-1 * times());
    };

    desc(History.back, "Go {count} pages back");

    History.forward = function() {
      return history.go(1 * times());
    };

    desc(History.forward, "Go {count} pages forward");

    return History;

  }).call(this);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.History = History;

}).call(this);
