// Generated by CoffeeScript 1.6.3
(function() {
  var Links, root;

  Links = (function() {
    var open, url, _i, _len, _ref;

    function Links() {}

    open = function(url) {
      return Post({
        action: "Tab.openUrl",
        url: url,
        newtab: CmdBox.get().content.indexOf("!") !== -1
      });
    };

    Links.downloads = function() {
      return open("chrome://downloads/");
    };

    Links.history = function() {
      return open("chrome://history/");
    };

    Links.chrome_help = function() {
      return open("chrome://help/");
    };

    Links.bookmarks = function() {
      return open("chrome://bookmarks/");
    };

    Links.settings = function() {
      return open("chrome://settings/");
    };

    Links.extensions = function() {
      return open("chrome://extensions/");
    };

    Links.github = function() {
      return open("https://github.com/jinzhu/vrome");
    };

    Links.issues = function() {
      return open("https://github.com/jinzhu/vrome/issues");
    };

    Links.options = function() {
      return open("/background/options.html");
    };

    _ref = ['downloads', 'bookmarks', 'history', 'chrome_help', 'settings', 'extensions', 'github', 'issues', 'options'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      url = _ref[_i];
      desc(Links[url], "Open " + url + ",! open in new page");
    }

    return Links;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Links = Links;

}).call(this);
