// Generated by CoffeeScript 1.6.3
(function() {
  var Scroll, root;

  Scroll = (function() {
    var horizontal_moment, vertical_moment;

    function Scroll() {}

    vertical_moment = 15;

    horizontal_moment = 15;

    Scroll.top = function() {
      return scrollTo(scrollX, 0);
    };

    desc(Scroll.top, "Scroll to the top of the page");

    Scroll.bottom = function() {
      return scrollTo(scrollX, document.body.scrollHeight);
    };

    desc(Scroll.bottom, "Scroll to the bottom of the page");

    Scroll.first = function() {
      if (times(true, true) === 0) {
        return scrollTo(0, scrollY);
      }
    };

    desc(Scroll.first, "Scroll to the left of the page");

    Scroll.last = function() {
      return scrollTo(document.body.scrollWidth, scrollY);
    };

    desc(Scroll.last, "Scroll to the right of the page");

    Scroll.up = function() {
      return scrollBy(0, times() * -vertical_moment);
    };

    desc(Scroll.up, "Scroll up");

    Scroll.down = function() {
      return scrollBy(0, times() * vertical_moment);
    };

    desc(Scroll.down, "Scroll down");

    Scroll.left = function() {
      return scrollBy(times() * -horizontal_moment, 0);
    };

    desc(Scroll.left, "Scroll left");

    Scroll.right = function() {
      return scrollBy(times() * horizontal_moment, 0);
    };

    desc(Scroll.right, "Scroll right");

    Scroll.nextPage = function() {
      return scrollBy(0, times() * window.innerHeight * 0.95);
    };

    desc(Scroll.nextPage, "Scroll down {count} full page");

    Scroll.prevPage = function() {
      return scrollBy(0, times() * -window.innerHeight * 0.95);
    };

    desc(Scroll.prevPage, "Scroll up {count} full page");

    Scroll.nextHalfPage = function() {
      return scrollBy(0, times() * window.innerHeight / 2);
    };

    desc(Scroll.nextHalfPage, "Scroll down {count} half page");

    Scroll.prevHalfPage = function() {
      return scrollBy(0, times() * -window.innerHeight / 2);
    };

    desc(Scroll.prevHalfPage, "Scroll up {count} half page");

    Scroll.toPercent = function() {
      return scrollTo(scrollX, times(true) * $(document).height() / 100);
    };

    desc(Scroll.toPercent, "Scroll to {count}% of the page");

    return Scroll;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Scroll = Scroll;

}).call(this);
