// Generated by CoffeeScript 1.6.3
(function() {
  var Window, root;

  Window = (function() {
    function Window() {}

    Window.create = function() {
      return Post({
        action: "Window.create"
      });
    };

    desc(Window.create, "Open a new window");

    Window.close = function() {
      return Post({
        action: "Window.close"
      });
    };

    desc(Window.close, "Close current window");

    Window.closeAll = function() {
      return Post({
        action: "Window.closeAll"
      });
    };

    desc(Window.closeAll, "Close all windows (quitall)");

    Window.only = function() {
      return Tab.close({
        type: "otherWindows"
      });
    };

    desc(Window.only, "Close other windows");

    Window.saveas = function(msg) {
      var filename;
      if (msg != null ? msg.filename : void 0) {
        return CmdBox.set({
          title: "Downloaded as '" + msg.filename + "'",
          timeout: 4000
        });
      } else {
        filename = CmdBox.get().argument;
        CmdBox.remove();
        return setTimeout(Post, 500, {
          action: "Window.save_page",
          filename: filename
        });
      }
    };

    desc(Window.saveas, "Save page as");

    Window.capture = function(msg) {
      if (msg != null ? msg.url : void 0) {
        Clipboard.copy(msg.url);
        return CmdBox.set({
          title: "Captured current window,<a href='" + msg.url + "' target='_blank'>Click to see the image</a>",
          timeout: 8000
        });
      } else {
        CmdBox.remove();
        return setTimeout(Post, 500, {
          action: "Window.capture"
        });
      }
    };

    desc(Window.capture, "Capture visible tab");

    return Window;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Window = Window;

}).call(this);
